### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by bonuschild** [xNul/code-llama-for-vscode#10]
As title this repository missing an official `requirements.txt` to guide developer to install dependencies. Will it come up later?

**Comment by xNul** [comment]
Since there is only one package (`flask`), I decided to not add a `requirements.txt` and simply include it in the instructions. This won't be added unless I start using many additional dependencies which is unlikely.

Closing this issue since your question has been answered and this issue is so old. Let me know if you'd like to reopen it.
